# Generated by Django 2.2.6 on 2019-10-14 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0004_invitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circle',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Date time on which the object was created.', verbose_name='modified at'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Date time on which the object was created.', verbose_name='modified at'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Date time on which the object was created.', verbose_name='modified at'),
        ),
    ]
