# Generated by Django 2.2.6 on 2019-10-14 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Date time on which the object was created.', verbose_name='modified at'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Date time on which the object was created.', verbose_name='modified at'),
        ),
    ]
